### PR TITLE
Create de_DE.po

### PR DESCRIPTION
**Pull request by Etamuk**

### CODE REVIEW

**Comment by p91paul** [comment]
hi, for other languages we also have the .mo committed, since it's easier for people to install from github if all the files are there. Can you please add it to this pr?

**Comment by Etamuk** [comment]
Hello,
oh, i didn't know that. I'm using Gtranslate and there is no export to .mo. So now i did this job with Poedit. While uploading the .mo Github "says" that this file type isn't supportet. So I made a zip file. 
I hope it's ok now. 

[MiddleClickClose.zip](https://github.com/p91paul/middleclickclose/files/3303003/MiddleClickClose.zip)

**Comment by p91paul** [comment]
well you could just commit the mo file and update the pull request!no need to upload it there.
Otherwise when I get some free time I can generate it, however that could take some weeks, unfortunately I'm not really using my personal pc recently.

**Comment by Etamuk** [comment]
Hm. Thank you. I am new to github and technically i don't know a lot about programming (mo or po file needed to compile). With poedit now i can commit the mo file too. 
I would update the po file text and attache the mo file (but uploading the mo file is only availible as archive). 
I think i have to learn more about it :smile:

**Pull request merged**
